# Docker Compose YML Config

# frontend:
#   image: jtarball/docker-polymer:latest
#   env_file:
#     - env
#   expose:
#     - "3000"



# Porting Mapping Only work on `docker compose up` not via `docker run`

# devmount:
#   restart: always
#   build: docker/devmount
#   volumes:
#     - mount:/src
#   volumes_from: 
#     - app


app:
  restart: always
  build: docker/app
  #command: python /mount/app/backend/manage.py runserver 0.0.0.0:8000
  env_file:
    - env
  volumes:
    - ./docker/app/app:/app
  ports:
    - "8000:8000"
  links:
    - postgres:postgres

# nginx:
#   restart: always
#   build: ./docker/nginx/
#   ports:
#     - "80:80"
#   volumes:
#     - /www/static
#   volumes_from:
#     - app
#   links:
#     - app:app

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"

data:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql